"""fistr migr

Revision ID: 3ffb5ce19c06
Revises: 
Create Date: 2025-09-10 16:04:55.467811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffb5ce19c06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('person_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
