name: Dipendenze tra jobs

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v
      - name: Run test
        run: echo "Test eseguito con successo"

  deploy-job:
    runs-on: ubuntu-latest
    
    needs: test-job
    steps:
      - name: Fake deploy
        run : echo "Questo si legge se è partito l'altro job (test-job)"

        