name: Test run.py

on:
  push:
    branches:
      - main
      - dev

jobs:
  run-python-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Esegui run.py
        run: python run.py