name : Workflow su container

on:
  workflow_dispatch:

jobs:
  containerr_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Esegui container
        run: docker-compose up -d  --build   

      - name: Esegui pytest dentro container
        run: docker-compose exec -T web pytest -v


      
          
